spring:
  application:
    name: movieflix

  datasource:
    url: jdbc:postgresql://localhost:5432/movieflix
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect # Corrigi "plataform" para "platform"
    hibernate:
      ddl-auto: none # <-- ADICIONE ESTA LINHA AQUI
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  security:
    user:
      name: admin
      password: 123

server:
  port: 8081